# Generated by Django 5.1.8 on 2025-05-06 19:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('tie', 'Tie')], max_length=10)),
                ('player_score', models.PositiveSmallIntegerField()),
                ('dealer_score', models.PositiveSmallIntegerField()),
                ('player_hand', models.TextField()),
                ('dealer_hand', models.TextField()),
                ('balance_change', models.IntegerField()),
                ('balance_before', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game History',
                'verbose_name_plural': 'Game Histories',
                'db_table': 'blackjack_gamehistory',
                'ordering': ['-created_at'],
            },
        ),
    ]
