#!/bin/bash

psql -U casinouser -d casinodb <<-EOSQL
    CREATE USER $SONAR_JDBC_USERNAME WITH PASSWORD '$SONAR_JDBC_PASSWORD';
    CREATE DATABASE sonar OWNER $SONAR_JDBC_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE sonar TO $SONAR_JDBC_USERNAME;
EOSQL