# Generated by Django 5.1.8 on 2025-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicegamemodel',
            name='bet',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dicegamemodel',
            name='payout',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
