# Generated by Django 5.1.8 on 2025-05-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_coin_balance_profile_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coin_balance',
        ),
    ]
